# Site settings
title: Plausible Enough
email: andynu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Let's make things together.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andynu.github.io" # the base hostname & protocol for your site
twitter_username: andynu
github_username:  andynu

# Build settings
markdown: kramdown
